# Generated by Django 5.2.6 on 2025-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
